name: PR Reviewer Checklist

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pr-checklist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run PR Checklist Validator
      run: |
        curl -X POST http://localhost:8080/checklist \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d '{"pr_number": "${{ github.event.pull_request.number }}"}'
